# Generated by Django 4.2.1 on 2023-05-24 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prince", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrinceRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Developer Role",
                "verbose_name_plural": "Developer Roles",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="prince",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="prince",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prince_role",
                to="prince.princerole",
            ),
        ),
    ]
