# Generated by Django 4.2.1 on 2023-05-24 20:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prince", "0003_princeprincenote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prince",
            options={
                "ordering": ["user__username"],
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
            },
        ),
        migrations.AlterModelOptions(
            name="princeprincenote",
            options={
                "ordering": ["prince_author__user__username", "prince__user__username"],
                "verbose_name": "Member Note",
                "verbose_name_plural": "Member Notes",
            },
        ),
        migrations.AlterModelOptions(
            name="princerole",
            options={
                "ordering": ["name"],
                "verbose_name": "Member Role",
                "verbose_name_plural": "Member Roles",
            },
        ),
    ]
