[tool.black]
py311 = true
max-line-length = 88
experimental-string-processing = true
include = ['devpalace/.*\.py$']
exclude = [".git", "__pycache__", "**/migrations/*", "venv", ]

[tool.isort]
profile = "black"
multi_line_output = 3
