# Generated by Django 4.2.1 on 2023-05-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("party", "0003_alter_partyprince_options_alter_partytype_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partyprince",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                ],
                default="waiting",
                max_length=100,
            ),
        ),
    ]
