# Generated by Django 4.2.1 on 2023-05-24 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("party", "0005_remove_partyprince_status_party_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="party_type",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="party_party_type",
                to="party.partytype",
            ),
            preserve_default=False,
        ),
    ]
